### ISSUE TITLE
Update docs to state webpack as a requirement

### ISSUE THREAD

**Issue by SeanPrashad** [react-figma/react-figma#100]
Recently I was exploring react-figma and came across an issue when trying to setup the project using the [current docs](https://github.com/react-figma/react-figma/blob/master/contributing.md#developing):

![image](https://user-images.githubusercontent.com/13009507/67947728-ac04df00-fbba-11e9-92c5-936459df7005.png)

It seems that webpack is required and so I had to globally install `webpack`, `webpack-cli`, and `webpack-dev-server` before attempting to run step #2 [here](https://github.com/react-figma/react-figma/blob/master/contributing.md#running-webpack-at-watch-mode).

The command I ran to install webpack on my system was `yarn global add webpack webpack-cli webpack-dev-server`.

Node version: `v12.12.0`
Yarn version: `1.19.1`

**Comment by SeanPrashad** [comment]
I'd like to submit a patch to update the docs if that's okay!

**Comment by ilyalesik** [comment]
I check it at VSCode embedded terminal, and it reproduced. Thanks for your contribution!
