### ISSUE TITLE
Create Image component

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#105]
* [react-sketchapp doc](http://airbnb.io/react-sketchapp/docs/API.html#image)
* [react-native doc](https://facebook.github.io/react-native/docs/image)

props:
* `source `
* `resizeMode`

Can just use `Rectangle` with `backgroundImage`.

**Comment by HVish** [comment]
I am working on this.

**Comment by ilyalesik** [comment]
@HVish That's great! 🤗

**Comment by HVish** [comment]
@ilyalesik resizeMode has follwoing modes:
`contain` | `cover` | `stretch` | `center` | `repeat` | `none`

but we have only two types of backgroundSizes: `cover` | `contain`
what should we do for other modes?

**Comment by ilyalesik** [comment]
Yeah, I see that we just convert `contain` to `scaleMode: FIT` and `cover` to `scaleMode: FILL`.

Figma has two others scale mods: CROP and TILE, [https://www.figma.com/plugin-docs/api/Paint/](https://www.figma.com/plugin-docs/api/Paint/) that can be used for implementing other resizeMode's: 
* `stretch ` is equal to `scaleMode: CROP` with `imageTransform` that set image aspect ratio equal to rectangle aspect ratio.
* `center` is equal to `scaleMode: CROP`.
* `repeat` is equal to `scaleMode: TILE`.
