### ISSUE TITLE
Create TextStyles module

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#110]
* [react-sketchapp doc](http://airbnb.io/react-sketchapp/docs/API.html#textstyles)

**Comment by zqwitt** [comment]
Also see figma api [TextStyle](https://www.figma.com/plugin-docs/api/TextStyle/), and [figma.createTextStyle](https://www.figma.com/plugin-docs/api/figma/#createtextstyle) and [figma.getLocalTextStyles()](https://www.figma.com/plugin-docs/api/figma/#getlocaltextstyles)

**Comment by ilyalesik** [comment]
The [Local Styles](https://react-figma.dev/docs/local-styles) API.
