### ISSUE TITLE
Group does not handle style prop

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#125]
Example:
```jsx
<Group name="Button" style={{ width: 200, height: 100, backgroundColor: '#12ff00', justifyContent: 'center', alignItems: 'center' }}>
    <Text characters="Button" />
</Group>
```
No style will be applied

**Comment by LosYear** [comment]
`Frame` component is affected too

**Comment by ilyalesik** [comment]
Design system example works fine. It contains frames with padding/margin styles. 
What styles is not applied?

**Comment by LosYear** [comment]
Try changing `Group` to `Frame` in the code above, it'll draw Frame with a white background instead of green. 
Spent some time investigating the issue, background in `FrameNode` seems to be handled via `backgrounds` attribute but it didn't used anywhere (only `fills`)

**Comment by ilyalesik** [comment]
I created issue with frame bug: #146
