### ISSUE TITLE
Implementing shadow style props

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#129]
https://react-figma.now.sh/docs/styling.html:

* shadowColor
* shadowOffset
* shadowOpacity
* shadowSpread
* shadowRadius

**Comment by HVish** [comment]
@ilyalesik I am confused with the type of `shadowOffset`
```typescript
{ width: number, height: number }
```
I think it should be offset relative to the node. Something like:
```typescript
{ x: number, y: number }
```
reference: [Effect - figma documentation](https://www.figma.com/plugin-docs/api/Effect/#shadoweffect)

**Comment by ilyalesik** [comment]
[react-native](https://facebook.github.io/react-native/docs/shadow-props) and react-sketchapp uses `{ width: number, height: number }` so it's preferable. 
I think, we can just convert `shadowOffset` like this:

```javascript
node.offset = {
  x: props.style.shadowOffset.width,
  y: props.style.shadowOffset.height
}
```

**Comment by HVish** [comment]
I would like to work on it.

**Comment by HVish** [comment]
@ilyalesik `shadowSpread` is not mentioned in [react-native](https://facebook.github.io/react-native/docs/shadow-props) documentation. What is the difference between `shadowRadius` and `shadowSpread`?

**Comment by ilyalesik** [comment]
Figma supported only blur radius, so I think we can just ignore `shadowSpread`.
