### ISSUE TITLE
Implementing borders style props support

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#139]
https://react-figma.now.sh/docs/styling.html

Props:
* borderColor
* borderTopColor
* borderRightColor
* borderBottomColor
* borderLeftColor

* borderWidth
* borderTopWidth
* borderRightWidth
* borderBottomWidth
* borderLeftWidth

`react-figma` already has `transformBorderStyleProperties` function.

Can be used Figma API (GeometryMixin):
```
strokes: ReadonlyArray<Paint>
```
and Yoga Layout:
```
setBorder(edge: YogaEdge, borderWidth: number): void;
```

**Comment by HVish** [comment]
@ilyalesik I am interested in doing this, but have some doubts. I tried searching in Figma api documentation and its features but I couldn't find that if they support borders for all sides individually. Can you suggest some alternative or what am I missing?

**Comment by ilyalesik** [comment]
Yes, indeed, I did not notice it. I think, we can just implementing `borderColor`, `borderWidth` only.

**Comment by HVish** [comment]
@ilyalesik can you help me with yoga-layout api? I am not able to find where to implement `setBorder()` function of yoga-layout. Should I use `yogaRef.current.setBorder()` inside `useYogaLayout()` hook?

**Comment by ilyalesik** [comment]
There is a much more suitable place - `src/yoga/applyStyleToYogaNode.ts`. 🙂
You can add something like 
```
    if (style.borderWidth) {
        yogaNode.setBorder(yoga. EDGE_ALL, style.borderWidth);
    }
```
to `applyStyleToYogaNode` function.

**Comment by HVish** [comment]
Thanks.

**Comment by ilyalesik** [comment]
Can I ask you mark `borderWidth` and `borderColor` as supported at `docs/styling.md`? Just replace ⛔to ✅.

**Comment by HVish** [comment]
Sure
