### ISSUE TITLE
Creating HMR (hot module replacement) example

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#15]
[react-hot-loader](https://github.com/gaearon/react-hot-loader) can used

**Comment by LosYear** [comment]
react-hot-loader doesn't seem to be relevant in the future. 
Probably, [react/react-refresh](https://github.com/facebook/react/tree/master/packages/react-refresh) should be used instead.

In this [https://github.com/facebook/react/issues/16604#issuecomment-528663101](thread) Dan clarifies how to use it
