### ISSUE TITLE
Help to setup & start react-figma via boilerplate

### ISSUE THREAD

**Issue by adryweber** [react-figma/react-figma#189]
Please, help me setup and start react-figma.

I, clone boilerplate, as describe at https://github.com/react-figma/react-figma-boilerplate

When i start webpack:watch, webpack is running, but folder dist is not created.

<img width="877" alt="Снимок экрана 2019-11-22 в 21 14 06" src="https://user-images.githubusercontent.com/15189959/69450046-4b0d9880-0d6d-11ea-98c4-1cbca767011c.png">

**Comment by ilyalesik** [comment]
Hi, @adryweber! I will fix it at `react-figma-boilerplate`, right now you can use workaround:

```js
var path = require("path");
var configure = require('react-figma-webpack-config');

module.exports = configure({
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'dist') // Compile into a folder called "dist"
    },
});
```

**Comment by adryweber** [comment]
@ilyalesik, many thanks. It, worked!
