### ISSUE TITLE
lineHeight unitless compatibility

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#190]
## What expected
`lineHeight` without unit should converted to percentage values, e.g.
`lineHeight: 1.4` -> `{value: 140, unit: "PERCENT"}`.

## What happens

`lineHeight` without unit converted to pixels, e.g. `lineHeight: 1.4` -> `{value: 1.4, unit: "PIXELS"}`.

**Comment by macintoshhelper** [comment]
Would be great if `lineHeight` could support pixels by default (for unitless use), as React Native and React Sketch.app do. This would be a breaking change though, and cause extra work for web.

`styled-components/primitives` converts `line-height: 20px` to `lineHeight: 20` for non-web platforms, which results in a 2000% line height, I can't think of any way to use pixel line heights in `styled-components/primitives`, as it can't return the `lineHeight: '20px'` (which would possibly crash React Native).

Related issue in the `styled-components` repo: https://github.com/styled-components/styled-components/issues/1643 .

This would require a processing layer for using multipliers in web as a target though, so am not sure on a nice way to solve this difference.

**Comment by ilyalesik** [comment]
Yes, it's not too easy. E.g. `react-native-web` converts `lineHeight: x` to `line-height: x` at CSS. Current implementation is compatible with it (converts to Figma code: `{ value: style.lineHeight * 100, unit: 'PERCENT' }`).

**Comment by ilyalesik** [comment]
Issue created #286
