### ISSUE TITLE
Creating Star component

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#20]
Figma API:

```javascript
createStar(): StarNode
```

**Comment by adzshaf** [comment]
I'm very interested in working on this issue. Any hints to do this? @ilyalesik Thank you!

**Comment by ilyalesik** [comment]
Hi, @adzshaf and welcome on board! 

`Star` component is similar to `Rectangle`. Check out `src/components/rectangle/Rectangle.tsx`. Also, `star` renderer needed. Look at `src/renderers/rectangle.ts`. 

You need to create `src/components/star/Star.tsx` and `src/renderers/star.ts`.

`Star` component should receive `pointCount` and `innerRadius` props. Like this:

```javascript
<Star pointCount={5} innerRadius={100} />
```

**Comment by adzshaf** [comment]
I see, thank you so much for your help. How do I know if `Star` works? @ilyalesik

**Comment by ilyalesik** [comment]
> How do I know if Star works?

I think, the best way is creating a new example at folder `/examples/all-components`, that create `Page` with all components. Initially, displaying `Star` is enough:  

```javascript
<Page name=`All components`>
    <Star pointCount={5} innerRadius={100} />
</ Page>
```

You can just copy `/examples/basic` folder. More info about creation examples and running: https://github.com/react-figma/react-figma/blob/master/contributing.md#running-examples.

I create issue `Adding all components to /examples/all-components` later.

**Comment by zqwitt** [comment]
@adzshaf Is there still interest in working on this. I too am also interested in working on this feature.
