### ISSUE TITLE
Nodes are positioned incorrectly with flexDirection changed after hydration

### ISSUE THREAD

**Issue by LosYear** [react-figma/react-figma#200]
**Given**
Let's assume we have the following code:
```javascript
<Page>
    <Frame style={{ flexDirection: 'row' }}>
        <Rectangle
            style={{
                width: 200,
                height: 100,
                backgroundColor: '#ff8b29'
            }}
        />
        <Rectangle
            style={{
                width: 200,
                height: 100,
                backgroundColor: '#008b29'
            }}
        />
    </Frame>
</Page>
```
**Steps to reproduce**
1. Initialy render following code
2. Change `flexDirection` to `column`
3. Render again on the same page (aka hydrate existing figma tree)

**What expected**

![image](https://user-images.githubusercontent.com/1065122/69870931-72f78180-12c2-11ea-862f-515e9910f88e.png)
 
**Got**

![image](https://user-images.githubusercontent.com/1065122/69871061-e00b1700-12c2-11ea-97ba-88c4ea094e33.png)

**Comments**

Seems like the bug is related to updating yoga props after recalculating layout

**Comment by ilyalesik** [comment]
Thanks!
