### ISSUE TITLE
Creating BooleanOperation component

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#23]
Figma API
```javascript
createBooleanOperation(): BooleanOperationNode
```

**Comment by HVish** [comment]
This API has been deprecated. Quoting the message mentioned in [figma's documetation.](https://www.figma.com/plugin-docs/api/properties/figma-createbooleanoperation/)

> [DEPRECATED]. Use figma.union, figma.subtract, figma.intersect, figma.exclude instead.
