### ISSUE TITLE
Implementing Auto-Layout properties on FrameNode

### ISSUE THREAD

**Issue by zqwitt** [react-figma/react-figma#245]
https://www.figma.com/plugin-docs/api/FrameNode/#auto-layout-properties

Auto Layout properties
**layoutMode: "NONE" | "HORIZONTAL" | "VERTICAL"**
Determines whether this layer uses auto-layout to position its children. Defaults to "NONE". [Read more]

**counterAxisSizingMode: "FIXED" | "AUTO"**
Applicable only on auto-layout frames. Determines whether the counter axis has a fixed length (determined by the user) or an automatic length (determined by the layout engine). [Read more]

**horizontalPadding: number**
Applicable only on auto-layout frames. Determines the horizontal padding between the borders of the frame and its children.

**verticalPadding: number**
Applicable only on auto-layout frames. Determines the vertical padding between the borders of the frame and its children.

**itemSpacing: number**
Applicable only on auto-layout frames. Determines distance between children of the frame.

**constraints: Constraints**
Constraints of this node relative to its containing FrameNode, if any.

**Comment by ilyalesik** [comment]
It definitely needs to be implemented. 😊

Notes:

* ComponentNode, FrameNode, InstanceNode are implements `DefaultFrameMixin` that contains Auto-Layout properties (not only FrameNode). 
* Right now Figma Auto-Layout cannot be a full-fledged replacement of Yoga Layout for implementing [layout styles](https://react-figma.now.sh/docs/styling#layout-styles).

**Comment by ilyalesik** [comment]
Has supported since v`0.0.47`
