### ISSUE TITLE
View with children doesn't support backgroundColor

### ISSUE THREAD

**Issue by macintoshhelper** [react-figma/react-figma#281]
Hi, thanks a lot for the new react-native/primitives style `<View>` and `<Text>` components!

I just tried using them to render a view with background colour, and some text, but am getting strange results.

Sample code:

```jsx
<View style={{ width: 200, height: 200, justifyContent: 'center', alignItems: 'center', backgroundColor: '#0ddd25' }}>
  <Text>
    Hello World
  </Text>
</View>
```

renders:
![image](https://user-images.githubusercontent.com/6757532/77969663-20ff5080-72e2-11ea-83ea-0399079fdba6.png)

and the group breaks when it's clicked on (width/height doesn't match up with the children).

However, this sample code works:

```jsx
<View style={{ width: 200, height: 200, justifyContent: 'center', alignItems: 'center', backgroundColor: '#0ddd25' }}>
  <View style={{ width: 200, height: 200, backgroundColor: '#0ddd25', position: 'absolute', left: 0, top: 0 }} />
  <Text>
    Hello World
  </Text>
</View>
```

![image](https://user-images.githubusercontent.com/6757532/77969717-4a1fe100-72e2-11ea-8490-451d5171dfca.png)

Maybe this could be fixed by injecting a Rectangle (or View with no children) into every View with children, as the first element, with the full width and height of the parent, and `position: absolute` together with `left: 0, top: 0`? I believe this is what `react-sketchapp` does.

**Comment by ilyalesik** [comment]
Please, check that you use the latest version of `react-figma` - currently it's `0.0.57`. I checked the issue at the latest version and green background was rendered:

<img width="502" alt="Screenshot 2020-04-01 at 11 38 37" src="https://user-images.githubusercontent.com/1270648/78117252-17730700-740e-11ea-84de-857390fad679.png">

**Comment by macintoshhelper** [comment]
Ah, sorry, I had generated a fresh project with the template and forgot to try updating to the latest version. I have this now 🙂:

![image](https://user-images.githubusercontent.com/6757532/78144803-fddeb900-7427-11ea-805b-e98cad74b873.png)

**Comment by ilyalesik** [comment]
Thanks! Probably I should bump `react-figma` version at `react-figma-boilerplate`. 🤔
