### ISSUE TITLE
Unitless lineHeight should be converted to pixels value

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#286]
E.g. `lineHeight: 20` should be converted to `{value: 20, unit: "PIXELS"}`. 

It's will be equals to `react-native` and `react-native-web` behavior.

[react-native-web: Fixing the lineHeight style property to match iOS and Android](https://github.com/necolas/react-native-web/pull/142)

**Comment by macintoshhelper** [comment]
👍. I think the problem with using a multiplier, is that it's a percentage of the *inherited* font size, which doesn't translate over to React Native/Figma/Sketch, etc, as there's no style cascading. It's an annoying limitation, but I think it makes sense to use line heights as pixels, for encapsulated styling, and to have a percentage/multiplier polyfill for web (without font-size inheritance/cascading).
