### ISSUE TITLE
Handle falsey 0px unit for `borderWidth`

### ISSUE THREAD

**Issue by macintoshhelper** [react-figma/react-figma#288]
I've run into a strange issue where I have `defaultProps = { borderWidth = 1 }`, then in a wrapping component I have `defaultProps = { borderWidth = 0 }`, and the intial `borderWidth: 1` remains. 0 unit resolved as false, when it can be a valid unit to pass through.

**Proposed fix:**

```js
// Add (borderWidth === 0) check
    if (styles.borderWidth || styles.borderWidth === 0) {
        props.strokeWeight = transformSize(styles.borderWidth);
    }
```

Maybe this should be a helper function `function isSet(styleUnit)`?

**Comment by ilyalesik** [comment]
The issue won't reproduce. The `geometryMixin` has a default for `strokes` prop, that's applied when `borderWidth = 0`.
