### ISSUE TITLE
Structuring design system with react-figma

### ISSUE THREAD

**Issue by kennetpostigo** [react-figma/react-figma#297]
Hi 👋

I'm currently a figma and react/react-native user. The little startup my friends and I are working on have several UI primitives that we use and compose together to create more complex UI. Currently we're in a situation where 
1. Our figma designs of our components get updated in figma and we have to go and update both our webapp and react-native app with the updates to those components.
2. Our components are updated in the webapp/react-native app and we have to go update the figma board to keep them in sync.

This wasn't much of an issue at first when we had 10 -30 components. But as our primitives got larger so did our "molecules" that are composed from primitives and updating all of them in figma and code is starting to become a full on task that is pretty tedious.

How can we leverage react-figma to mitigate this issue? We're not design or design-system experts by any means but this has been a pain point for us and really would prefer to create a component-library that we would import into our application and have things "just work".

We also use `emotion` for styling our webapp and react-native app so we're not quite sure how much of a barrier that is.

Would love any insight into this 🙏

**Comment by ilyalesik** [comment]
Hi!

> How can we leverage react-figma to mitigate this issue?

You can try to render your current react-native components at Figma through `react-figma` and webpack aliasing (see PrimeDemo example below). If it's working, you can use React components as single source of truth for design, and update figma designs through rendering changed components at Figma.

There are links that can help you:
* [PrimerDemo](https://github.com/react-figma/PrimerDemo) - multiplatform design-system.
* [styled-components](https://github.com/react-figma/react-figma/tree/master/examples/styled-components) - using `react-figma` with styled-components.
* [react-primitives](https://github.com/lelandrichardson/react-primitives) - primitive react components.

Also, we can continue the discussion at some chat or schedule a call. 🙌

**Comment by kennetpostigo** [comment]
@ilyalesik Thank you for the links! Does react-figma have a discord server?

**Comment by ilyalesik** [comment]
react-figma haven't Discord, right now there is [Spectrum](https://spectrum.chat/react-figma). Also, I can send you invite to Slack.

**Comment by kennetpostigo** [comment]
I believe GitHub is shutting down spectrum soon, my email is kennetfpostigo@gmail.com if you can send the slack invite there

**Comment by ilyalesik** [comment]
I will migrate to GitHub Discussions ASAP, right now it's not available (in the repo/org).

I have sent invite to Slack. 👌

**Comment by leggomuhgreggo** [comment]
Oh man! Had the same sort of questions. Would love to join y'all on Slack, as long as I'm not imposing

🙏  gwestneat@gmail.com  🙏

**Comment by ilyalesik** [comment]
@leggomuhgreggo I sent you invite. 🙌

**Comment by macintoshhelper** [comment]
Hi, to share code between web, React Native and React Figma, I would recommend building a React Native/Primitives component library with `react-primitives` (together with `@emotion/primitives` if you'd like to use Emotion). This can be in a separate directory, or bundled with Rollup – creating a build for each platform using platform extension cascading.

So long as your primitive UI components render the same cross-platform, you can build UIs with them that remain cross-platform.

Here's one pattern that could be used: https://github.com/elemental-design/primer-components/blob/master/src/Button.js

With a `styled-components` (or can be emotion) polyfill to make `styled.div` work: https://github.com/elemental-design/primer-components/blob/master/figma/src/styled.js . Or can just use `react-native-web`, there may be issues with Emotion SSR though with `react-native-web`.

Getting it production ready may be some work though (especially if you want to use SSR, code splitting, etc).
