### ISSUE TITLE
Replace figma.d.ts with @figma/plugin-typings package

### ISSUE THREAD

**Issue by LosYear** [react-figma/react-figma#317]
Figma provides official npm package which includes typings for Figma API, so I guess we should no longer keep `figma.d.ts` file in repo explicitly

Transition to typing package probably includes:
1. Updating `tsconfig.json` in the root of repo
2. Updating all `tsconfig.json` stored in plugins folders

Source: https://www.figma.com/plugin-docs/api/typings/

**Comment by ilyalesik** [comment]
Yes, I agree with it. 🙌
