### ISSUE TITLE
Implement Dimensions API

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#321]
[React Native Dimensions](https://reactnative.dev/docs/dimensions)

**Comment by macintoshhelper** [comment]
Hi, should be fairly straight forward to start with implementing the `useWindowDimensions` hook first? The `Frame` or `Artboard` components can wrap a React context provider, and `useWindowDimensions` can subscribe to the context state to get the width/height.

If `Dimensions` can be implemented inside the reconciler eliminating the need for hooks, this may be better/more stable though.
