### ISSUE TITLE
react-figma"' has no exported member 'subscribeOnMessages'.

### ISSUE THREAD

**Issue by asaadmahmood** [react-figma/react-figma#325]
Getting these various errors when I run watch.

![Screenshot 2020-07-17 at 1 29 42 AM](https://user-images.githubusercontent.com/11034289/87719576-fec80a80-c7cc-11ea-9b60-0b8872ca047a.png)

**Comment by ilyalesik** [comment]
Hi, @asaadmahmood! `subscribeOnMessages ` was removed at the `v0.1.0` version. You can update the `react-figma` imports according to [example](https://github.com/react-figma/react-figma/tree/master/examples/basic) or [doc](https://react-figma.now.sh/docs/configure#configure-main-thread).
