### ISSUE TITLE
Implementing rectangle radius support

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#34]
Figma API:

```typescript
  topLeftRadius: number
  topRightRadius: number
  bottomLeftRadius: number
  bottomRightRadius: number
```

Also, `style` support needed:
```typescript
borderRadius: number
borderBottomLeftRadius: number
borderBottomRightRadius: number
borderTopLeftRadius: number
borderTopRightRadius: number
```

**Comment by HVish** [comment]
@ilyalesik I would like to work on it. I have a question, should I add these properties to `LayoutStyleProperties` or create separate interface?

**Comment by ilyalesik** [comment]
Hey, @HVish! Only a rectangle **supports** radius. `LayoutStyleProperties` is more general interface. So, I think that only changes at `src/components/rectangle/Rectangle.tsx` and `src/renderers/rectangle.ts` needed.  Interface can look like this:

```typescript
interface RectangleProps extends DefaultShapeProps {
    style?: LayoutStyleProperties & GeometryStyleProperties & {borderRadius: number, ...}; // extend style properties
    children?: undefined;
    topLeftRadius: number; // support 'direct' properties
    topRightRadius: number;
    ...
}
```

`rectangle.ts` should handle `topLeftRadius` etc. props (`propsAssign` helper function can be used). `Rectangle.tsx` should handle style property that can contain `borderRadius: number` etc.

```jsx
<Rectangle style={{borderRadius: 10}} />
```

equal to

```
rect.topLeftRadius  = 10;
rect.topRightRadius  = 10;
rect.bottomLeftRadius  = 10;
rect.bottomRightRadius  = 10;
```
