### ISSUE TITLE
Configuration for noobs

### ISSUE THREAD

**Issue by akanoodles** [react-figma/react-figma#340]
![Screenshot 2020-08-12 at 19 17 55](https://user-images.githubusercontent.com/1613697/90052163-a4896f00-dcd0-11ea-89aa-80f317b91123.png)

So where does the above this code go? 

My webpack.config.js file looks like this:
![Screenshot 2020-08-12 at 19 22 21](https://user-images.githubusercontent.com/1613697/90052553-35604a80-dcd1-11ea-9d00-21565f90fa52.png)

**Comment by ilyalesik** [comment]
It will be use default webpack config (webpack.config.js). 

Are you have a problem with launching Webpack?
