### ISSUE TITLE
Question: will figma's new layout replace yoga?

### ISSUE THREAD

**Issue by jaketodaro** [react-figma/react-figma#352]
With figma releasing a more powerful layout mechanism in November 2020, will this library be able to replace yoga for layout and just use figma layout?

**Comment by ilyalesik** [comment]
There are no technical limitations for it, so when Figma API fits all [styles] (https://react-figma.now.sh/docs/styling), we could easily replace Yoga.

Right now it's possible to use Auto Layout props [directly] (https://github.com/react-figma/react-figma/blob/master/src/types.ts#L152), but it's not compatible with other APIs such a React Native.
