### ISSUE TITLE
Implementing presets for Frame component

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#38]
Preset should set default width, height, and name.

As an example, 
```javascript
<Frame preset={FRAME_PRESETS.iPhoneX} />
```
equal to
```javascript
<Frame name="iPhone X" width={375} height={812} />
```

The package should export `FRAME_PRESETS` variable, that contains all of presets available at Figma. It is proposed to use CamelCase for `FRAME_PRESETS` keys naming.

## List of presets available at Figma:

Phone

* **iPhone X** 375x812
* **iPhone 8 Plus** 414x736
* **iPhone 8** 375x667
* **iPhone SE** 320x568
* **Google Pixel 2** 411x731
* **Google Pixel 2 XL** 411x823
* **Android** 360x640

Tablet

* **iPad Mini / 9.7** 768x974
* **iPad Pro 10.5** 834x1112
* **iPad Pro 12.9** 1024x1366
* **Surface Pro 3** 1440x990
* **Surface Pro 4** 1368x912

Desktop

* **Desktop** 1440 x 1024
* **Macbook** 1152x700
* **Macbook Pro** 1440x900
* **Surface Book** 1500x1000
* **iMac** 1280x720

Watch

* **Apple Watch 42mm** 156x195
* **Apple Watch 38mm** 136x170

Paper

* **A4** 595x842
* **A5** 420x595
* **A6** 297x420
* **Letter** 612x792
* **Tabloid** 792x1224

Social Media

* **Twitter Post** 1012 x 506
* **Twitter Header** 1500 x 500
* **Facebook Post** 1200x630
* **Facebook Cover** 820x312
* **Instagram Post** 1080x1080
* **Instagram Story** 1080x1920
* **Dribbble Shot** 400x300
* **Dribbble Shot HD** 800x600
* **LinkedIn Cover** 1584x396

**Comment by HVish** [comment]
@ilyalesik I would like contribute on it.

**Comment by ilyalesik** [comment]
Welcome on board, @HVish! I am very glad to see you here. 🙂
