### ISSUE TITLE
Is react-figma suitable for web only cases? 

### ISSUE THREAD

**Issue by Wyctus** [react-figma/react-figma#402]
I can't find anything in the docs about using `react-figma` with simple HTML tags. Is there any way to use it without `<View>`, `<Text>`, e.g.? It would be really nice to use it with component libraries like `react-bootstrap` which are built upon `<div>`s, `<span>`s, etc.

**Comment by ilyalesik** [comment]
`div`, `span`, etc. tags are not a problem. But CSS is a problem, because too many css specifications is hard to implement on the current stack (Figma Plugins API + Yoga Layout for flexes):
* CSS Grid Layout
* pseudo classes, pseudo selectors
* ...

**Comment by Wyctus** [comment]
Yes, this is what I thought too. So my only option is to use `StyleSheet`, right?

**Comment by ilyalesik** [comment]
@Wyctus not only, it's also possible to use styled-components: [example](https://github.com/react-figma/react-figma/tree/master/examples/styled-components)

**Comment by Wyctus** [comment]
This looks great, thank you!
