### ISSUE TITLE
Doc unclear, only local dev support?

### ISSUE THREAD

**Issue by JulienDemarque** [react-figma/react-figma#452]
I couldn't understand from the doc the scope of react-figma. Is it possible to run react-figma on a server and have any user connect figma desktop plugin to it? or is this only a local development tool?

**Comment by ilyalesik** [comment]
Hey! Currently it's only a local development tool. But I think it's possible to build a plugin and distribute.

**Comment by JulienDemarque** [comment]
Thanks for the clarification.
