### ISSUE TITLE
Using useTextStyle cause font load issues

### ISSUE THREAD

**Issue by momsse** [react-figma/react-figma#453]
Hello,

Thanks for the great job done on that project.

I'm actually experiencing a strange issue when using `useTextStyle` hook. For the same style the one that do not use the local style stored on Figma with the hook work as expected (using the correct font weight). The one with the hook fail with the following error in the console:

```
rpc.js:136 Uncaught (in promise) Error: in set_fontName: Cannot use unloaded font "SF Pro Display SemiBold". Please call figma.loadFontAsync({ family: "SF Pro Display", style: "SemiBold" }) and await the returned promise first.
    at callback (<anonymous>:859:25)
    at handleRpc (<anonymous>:800:7)
    at handleRaw (<anonymous>:774:5)
    at onmessage (<anonymous>:733:24)
```

Here the minimal example:

```typescript
import React from 'react';
import { Frame, Page, StyleSheet, Text, useTextStyle } from 'react-figma';
import { FRAME_PRESETS } from 'react-figma/components/frame/Frame';

const style = StyleSheet.create({
  text: {
    fontFamily: 'SF Pro Display',
    fontSize: 20,
    fontWeight: '600',
  },
});

export default function FigmaApp() {
  const textStyle = useTextStyle(style.text, { name: 'header/h1' });

  return (
    <Page isCurrent name="Styleguide" style={{ flexDirection: 'row' }}>
      <Frame
        name="Typography"
        preset={FRAME_PRESETS.a4}
        style={{
          backgroundColor: 'white',
          marginRight: 48,
        }}
      >
        <Text style={style.text}>
          SF Pro Display without using local styles (and textStyleId)
        </Text>
        <Text style={textStyle}>
          SF Pro Display using local styles (and textStyleId)
        </Text>
      </Frame>
    </Page>
  );
}

```

<img width="1074" alt="Capture d’écran 2021-07-19 à 21 37 09" src="https://user-images.githubusercontent.com/1344228/126217129-5232c1fa-1438-404b-8d17-fb8d00fe4a6e.png">

When I remove the generated `textStyleId` key things works again ;-/ FYI all works as expected with `Roboto`. And I'm on Mac and have `SF Pro Display` and all his variants correctly installed.

Thanks for the help, 🙏

Edit 1: `fontWeight: 700` (Bold) works well in both cases, it seems related to font variant naming `Semibold` on Figma, trying and failing to load `SemiBold` on the console

**Comment by ilyalesik** [comment]
A simple workaround:

```
const style = StyleSheet.create({
    text: {
        fontFamily: 'SF Pro Display',
        fontSize: 20,
        // @ts-ignore
        fontWeight: 'Semibold',
    },
});
```

**Comment by ilyalesik** [comment]
Let's try `react-figma@0.17.1` - it's render the minimal example as well (but still have an error message)

**Comment by ilyalesik** [comment]
Thank you very much for reporting a problem!

**Comment by momsse** [comment]
Thanks for the help, will try the upgrade for sure 👌
