### ISSUE TITLE
Examples package.json doesn't have dependencies or DevDependencies 

### ISSUE THREAD

**Issue by oSethoum** [react-figma/react-figma#467]
This is the basic example in your examples it has no dependencies nor dev dependencies so whenever i try to yarn install i get nothing plus if i do it manually i get a lot of errors . please add the dependencies.

**Comment by ilyalesik** [comment]
Hey! You can just do `yarn install` in the root folder, and all plugins should works after that

**Comment by oSethoum** [comment]
this is a screenshot from the examples section in the repo: 
![image](https://user-images.githubusercontent.com/88779394/129564149-2f06073c-121f-4302-ba10-409b32053458.png)
notice that there is ne dependencies, how can yarn figure what to install right ?

**Comment by ilyalesik** [comment]
@oSethoum I mean that you need to install deps in the react-figma project root dir. So, the package.json is https://github.com/react-figma/react-figma/blob/master/package.json. After installing you will have a /react-figma/node_modules folder, and will can to run the "webpack:watch" script in the /react-figma/examples/basic-hmr folder

**Comment by YanisKondakov** [comment]
@ilyalesik
It does not work as you can see on screenshot below.
I made all steps and get error.
![EDF44216-0854-488B-BD05-F4AB9013D151](https://user-images.githubusercontent.com/19660005/152679411-9dd73f10-6933-4cd7-8eec-d5959dcd9547.jpeg)

**Comment by ilyalesik** [comment]
@YanisKondakov look like `yarn install` didn't install webpack cli. Or yarn command can't use weback installed locally. What are you thing, what's best solution here?
