### ISSUE TITLE
Add examples with a plugin UI

### ISSUE THREAD

**Issue by gengwang** [react-figma/react-figma#475]
I want to control the state of my Figma canvas via the plugin UI, but can't figure out how. Now all the examples appear to be "headless", even the _interactive_ example:

`figma.showUI(__html__, { visible: false });`

**Comment by ilyalesik** [comment]
Should be useful!

**Comment by ilyalesik** [comment]
I have added an example https://github.com/react-figma/react-figma/tree/master/examples/ui
