### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by YanisKondakov** [react-figma/react-figma#493]
Hello.

First of all, I want to say thank you for this idea. I watched videos of Ilia Lesik on youtube about cross-platform design system. And the idea is awesome.

But last week I tried to implement react-figma with react-native and..everything was broken. The getting start guide is not work. react-figma-boilerplate did not work cause of webpack 4. When I tried to import manifest.json into figma via plugins, there was the error. There were a lot of errors in terminal. So, if you need any help for update support, I have some time.

So, if project is not maintained anymore, please let us know the reasons.

**Comment by ilyalesik** [comment]
The project is maintained. It's would be very helpful if you could contribute anything. Let's create separated issues firstly. 🙌
