### ISSUE TITLE
so what about figma to react components?

### ISSUE THREAD

**Issue by quaj** [react-figma/react-figma#5]
I don't know how to we design React with Figma
Can you explain?

**Comment by ilyalesik** [comment]
Hi, @quaj! Are you mean how design process should look like with react-figma?

**Comment by quaj** [comment]
Hi @ilyalesik , my question is how to design react with Figma, I have searched google but seems not positive. The reason I'm here because I think you have a great experience with Figma.
Many thanks, love Figma but don't know how to start

**Comment by quaj** [comment]
Does it need we see the image/ design page to write again? Looks that way will take many times to design css again

**Comment by ilyalesik** [comment]
> I think that good if we can export all of one file to React components
React Figma provide the opposite way: describing design system through React components and rendering it at Figma. Probably, you needed [Figma to React converter](https://github.com/figma/figma-api-demo/tree/master/figma-to-react).

**Comment by quaj** [comment]
> React Figma provide the opposite way: describing design system through React components and rendering it at Figma. Probably, you needed [Figma to React converter](https://github.com/figma/figma-api-demo/tree/master/figma-to-react) [](/figma/figma-api-demo/tree/HEAD@{2019-09-20T10:52:42Z}/figma-to-react).

Thanks, I have tried it but not works. Will try again in another day
I think need delete this no related issue
