### ISSUE TITLE
Text children

### ISSUE THREAD

**Issue by macintoshhelper** [react-figma/react-figma#50]
Hi, it would be great to be able to use `<Text>` with children instead of having the `characters` prop.

I've implemented a basic form of this using `react-reconciler` in my [`react-xd`](https://github.com/macintoshhelper/react-xd) project, maybe the code there may be of help:

> https://github.com/macintoshhelper/react-xd/blob/master/src/renderer.js#L55

I think the main parts are:

```js
  shouldSetTextContent: (type, props) => {
    return (
      typeof props.children === 'string' ||
      typeof props.children === 'number'
    );
  },
```

and

```js
  createTextInstance: (
    text,
    rootContainerInstance,
    hostContext,
    internalInstanceHandle
  ) => {
    return createInstance(
      { type: 'text', props: { children: text } },
      rootContainerInstance
    );
    // return document.createTextNode(text);
  },
```

More work may be required to support nesting with text ranges (#32) though, React Native's reconciler may have some context on that.

**Comment by ilyalesik** [comment]
I think, we should consider passing text through `children`. `characters` prop is just 1:1 analog of [TextNode field](https://www.figma.com/plugin-docs/api/TextNode/#characters).
