### ISSUE TITLE
ComponentNode renderer should not implement geometryMixin

### ISSUE THREAD

**Issue by HVish** [react-figma/react-figma#52]
According the figma [component-node api](https://www.figma.com/plugin-docs/api/ComponentNode/), the `Geometry-related properties` are **not** included in component-node but geometryMixin has been implemented for component-node.

https://github.com/react-figma/react-figma/blob/eea041183d34c215b91571173adb7ba5221bfe93/src/renderers/component.ts#L15

**Comment by HVish** [comment]
FrameNode also have same issue

**Comment by ilyalesik** [comment]
Yeah, I agree with it. 👌
