### ISSUE TITLE
What's the purpose of this project?

### ISSUE THREAD

**Issue by ulitiy** [react-figma/react-figma#527]
It's really impressive what this project can do but what's the initial problem it solves?
I'd want to use the project but I don't really see any use cases for it.

It would be useful to mention that on the website and in the project description in the first paragraph.

There's a "getting started" page but no page "why would you get started at all?".

**Comment by ulitiy** [comment]
> A React renderer for Figma where we can use React components as a source for our Figma designs, pretty self-explanatory

Yeah, I figured. But why?

If you can use React as source of your design, you can just use it as a source of the end product - web page or an app.

**Comment by vikasbhalla05** [comment]
> > A React renderer for Figma where we can use React components as a source for our Figma designs, pretty self-explanatory
> 
> Yeah, I figured. But why?
> 
> If you can use React as source of your design, you can just use it as a source of the end product - web page or an app.
> 
> Any examples when it's useful?

I also at first sight of the project, thought the same thing 
why though create Figma design using React Component
while the Product cycle goes opposite to it ?

**Comment by Bijiabo** [comment]
I think I can explain this from the Figma plugin developer's point of view.

When I try to develop a plugin that needs to dynamically generate a screen for the user based on some data, there needs to be a good way to bind the elements on the interface. I think the react-figma is a good way for me.

**Comment by ulitiy** [comment]
> I think I can explain this from the Figma plugin developer's point of view.
> 
> When I try to develop a plugin that needs to dynamically generate a screen for the user based on some data, there needs to be a good way to bind the elements on the interface. I think the react-figma is a good way for me.

Makes sense. Does it integrate well with the design made in figma itself? Do you generate some elements and then put them in the context, what's your workflow? Because if you don't integrate the generated elements into the rest, you could totally do that with react in browser without figma completely.

**Comment by Bijiabo** [comment]
> > I think I can explain this from the Figma plugin developer's point of view.
> > When I try to develop a plugin that needs to dynamically generate a screen for the user based on some data, there needs to be a good way to bind the elements on the interface. I think the react-figma is a good way for me.
> 
> Makes sense. Does it integrate well with the design made in figma itself? Do you generate some elements and then put them in the context, what's your workflow? Because if you don't integrate the generated elements into the rest, you could totally do that with react in browser without figma completely.

My application scenario is simple, just generate some prototype interface through parsing Markdown text.

Of course, I can deploy the webpage myself to accomplish this. But for publish in Figma, I can share directly with others for no server, and we can discuss and add some comments on it.

**Comment by tjharrop** [comment]
In the design systems world, generating a figma library from the same raw data as code means you're guaranteed they match. Designers can then use figma to create designing, knowing that when a developer accesses the same component they are going to get the same thing.
