### ISSUE TITLE
Configuring GitBook

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#55]
Also, Now configuration needed.

**Comment by nik72619c** [comment]
Would like to have some more light on this one !

**Comment by ilyalesik** [comment]
Hey, @nik72619c!

You can use [this repo](https://github.com/tverio/community) as example. Configuration files:
* book.json - [gitbook](https://github.com/GitbookIO/gitbook) configuration file
* now.json - [deployment](https://zeit.co/docs/v2/advanced/configuration) configuration file
* Summary.md - book content file. Links to `contributing.md`, `CODE_OF_CONDUCT.md` and `docs/architecture.md` needed.
Also changes at package.json needed. Installed gitbook dependencies and scripts for book building.
