### ISSUE TITLE
Installation error: node engine

### ISSUE THREAD

**Issue by jac31885** [react-figma/react-figma#593]
I am trying to utilise this but getting the following error on installation. 

**error react-figma@0.30.0:** The engine "node" is incompatible 
with this module. Expected version ">=10.0.0 <17.0.0". Got "19.4.0"

**Comment by ilyalesik** [comment]
Hey @jac31885! Let install `react-figma@0.31.0`

**Comment by jac31885** [comment]
Great thanks. Will give that a go
