### ISSUE TITLE
Code behaving weirdly 

### ISSUE THREAD

**Issue by ZeroCool00** [react-figma/react-figma#62]
```
import * as React from 'react';
import { Page, Rectangle, Text, Frame } from 'react-figma';

// import { data } from './Helper/data';

const frameProps = {
    style: { paddingTop: 10, paddingBottom: 10, paddingLeft: 10, paddingRight: 10 }
};

const RenderData = () => {
    return (
        <Frame name="Column" {...frameProps}>
            <Text characters={'Space'} fontSize={14} />
        </Frame>
    );
};

export const App = () => {
    return (
        <Page name="New page">
            <RenderData />
        </Page>
    );
};
```

OutPut

<img width="1399" alt="Screenshot 2019-10-09 at 10 25 55 AM" src="https://user-images.githubusercontent.com/18139594/66454077-3195e300-ea84-11e9-9fe4-025a37b6186f.png">

I add fontSize `14` but its not showing `14` as you can font is too big,
And what's this error, is my code wrong here.

**Comment by ilyalesik** [comment]
Hi, @ZeroCool00! What text size did you receive? Can you click text and screenshot text properties panel? I can't reproduce the bug.
