### ISSUE TITLE
Renderer falls with the error when trying to the remove existing node during hydration

### ISSUE THREAD

**Issue by LosYear** [react-figma/react-figma#87]
## Given
Simple layout with 3 different `<Rectangle>` components. 

## Steps to reproduce
1. Add plugin to Figma
2. Run plugin on a new Figma document, it will 3 rectangle nodes
3. Comment out one of the `<Rectangle>`, for example, the second one
4. Run plugin again

## What expected
One of the nodes have to be removed from the document tree

## What happens
```
The above error occurred in the <page> component:
    in page
    in Unknown
    in Unknown
    in Unknown

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

Digging further gives us more precise error:

```
in get_parent: The node with id "1:91" does not exist"
```

Seems to be the problem with the hydration mechanism but needs more investigation

Link to reproducible code example: https://github.com/LosYear/react-figma-hydration-bug-example

**Comment by ilyalesik** [comment]
Fixed at v0.0.1-alpha.9.
