### ISSUE TITLE
Dynamic support at groups

### ISSUE THREAD

**Issue by ilyalesik** [react-figma/react-figma#97]
E.g.

```javascript
const App = () => {
   const [haveGroup, setHaveGroup] = React.useState(false);
   React.useEffect(() => {
     setTimeout(() => setHaveGroup(true), 1000);
   }, []);

   const rect = <Rectangle name="1.1" style={{ width: 200, height: 100, backgroundColor: '#f24e1e' }} />;
   
   return <>
      {haveGroup ? <Group>{rect}</Group> : rect}
   </>
};
```

**Comment by LosYear** [comment]
This case doesn't seem to be a valid right now as actual grouping executed on `commitMount` of `Page` component and it's only called once after page initially appended to the document

**Comment by ilyalesik** [comment]
I think, also test at `src/__tests__/renderer.test.tsx` needed. [Timer Mocks](https://jestjs.io/docs/en/timer-mocks) and `wait` from [react-testing-library](https://github.com/testing-library/react-testing-library) are useful for it.

**Comment by ilyalesik** [comment]
Priority changed to major because View component based on Group component and any other issues about dynamic things (e.g. #119) can be blocked by this issue.
